### ISSUE TITLE
Error: Cannot find module 'ngrok'

### ISSUE THREAD

**Issue by JamesGreenaway** [stevenkaspar/gatsby-plugin-ngrok-tunneling#1]
I am unable to use this plugin. I have added it to my gatsby-config.js and installed it via npm. However when I run <code>gatsby develop --https</code> it prints the above message. Do you have any advice?

**Comment by martimarkov** [comment]
Install ngrok using npm:

`npm install --save ngrok`

**Comment by jdfm** [comment]
The code pattern that is being used in the plugin makes me think it was developed for ngrok v2. If that is the case, note that the ngrok npm package [recommends](https://www.npmjs.com/package/ngrok#usage) specifically installing v2.3.0.

**Comment by TylerBarnes** [comment]
To confirm, this only works for me on v2.3.0

Weirdly HMR works from my ngrok url on my computer but I have to refresh my phone..
