### ISSUE TITLE
Stuck in onPreBootstrap

### ISSUE THREAD

**Issue by nxz91** [stevenkaspar/gatsby-plugin-ngrok-tunneling#2]
Hey,

I have installed the plugin, added ngrok using yarn, then did gatsby develop and now I am stuck in onPreBootstrap. Any ideas?

Thanks!
Leonard

**Comment by stevenkaspar** [comment]
I think @jonasho fixed this with his PR

**Comment by nxz91** [comment]
Amazing, thanks!
